name: CI

on:
  push: # run on every push (any branch)
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ hashFiles('**/pyproject.toml', '**/requirements*.txt', '**/setup.cfg', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install deps (pip)
        run: |
          python -m pip install --upgrade pip
          # If you have extras for dev: pip install -e .[dev]
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi
          pip install -e .
          # Ensure pytest is present even without reqs-dev
          python - <<'PY'
          import importlib, sys
          try:
              importlib.import_module("pytest")
          except ImportError:
              sys.exit(1)
          PY
        shell: bash

      - name: Run tests
        run: |
          pytest -q
