{% set name = "bvalcalc" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: # This will be filled in by conda-forge

build:
  number: 0
  noarch: python
  entry_points:
    - bvalcalc = Bvalcalc.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=3.10
    - numpy >=1.22
    - scipy >=1.13
    - matplotlib
    - seaborn >=0.13.2,<0.14.0

test:
  imports:
    - Bvalcalc
    - Bvalcalc.core
    - Bvalcalc.utils
  commands:
    - pip check
    - bvalcalc --help
  requires:
    - pip

about:
  home: https://github.com/JohriLab/Bvalcalc
  license: GPL-3.0-only
  license_family: GPL
  summary: Calculate relative diversity (B) under background selection
  doc_url: https://JohriLab.github.io/Bvalcalc/
  dev_url: https://github.com/JohriLab/Bvalcalc

extra:
  recipe-maintainers:
    - jacobimarsh
